version: "3.8"

services:
  process-definition-service:
    build:
      context: ./microservice
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - integration_network

  industry-connect-service:
    build:
      context: ./industry_connect_service
    ports:
      - "8001:8000"
    env_file:
      - .env
    networks:
      - integration_network

  integration-service:
    build:
      context: ./integration_service
    ports:
      - "8004:8000"
    environment:
      - PROCESS_SERVICE_URL=http://process-definition-service:8000
      - INDUSTRY_SERVICE_URL=http://industry-connect-service:8000
    depends_on:
      - process-definition-service
      - industry-connect-service
    networks:
      - integration_network

networks:
  integration_network:
    driver: bridge